apiVersion: apps/v1
kind: Deployment
metadata:
  name: department
  labels:
    app: department
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department
  template:
    metadata:
      labels:
        app: department
    spec:
      containers:
      - name: department
        image: krkn/department:1.0
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql
              key: mysql_host
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql
              key: root
        - name: MYSQL_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mysql
                key: department-database-name
        - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: rootpass
---
apiVersion: v1
kind: Service
metadata:
  name: department
  labels:
    app: department
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: department